
-   id: ceader
    name: ceader
    description: ''
    entry: ceader
    language: python
    'types_or': [python, pyi]
    args: ["--mode",'--files-dir','--header-path','--extensions-list']
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
