
-   id: ceader
    name: ceader
    description: 'Tool for automatically adding a header to files in the form of a comment'
    entry: ceader
    language: python
    args: ["--mode",'--header-path','--extensions','--skip-hidden','--debug','--files']
    require_serial: true
